#
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
#
---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
      include: scope
    assignees:
      - DaisyDomergue
    labels:
      - ci
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      include: scope
    labels:
      - build
  - package-ecosystem: npm
    directory: /rest-e2e-tests
    schedule:
      interval: weekly
    commit-message:
      prefix: test
      include: scope
    labels:
      - test
