
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Helsinki"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "kare"
    assignees:
      - "kare"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Helsinki"
    commit-message:
      prefix: "build"
      include: "scope"
    reviewers:
      - "kare"
    assignees:
      - "kare"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Helsinki"
    commit-message:
      prefix: "build"
      include: "scope"
    reviewers:
      - "kare"
    assignees:
      - "kare"
