LANG := en_US.UTF-8
SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c # run '/bin/bash ... -c /bin/cmd'

.PHONY: validate-swagger
validate-swagger:
	if ! curl --silent --fail --max-time 5 -o /dev/null https://validator.swagger.io; then \
       echo "Skipping Swagger validation since swagger.io is down" 1>&2;\
       exit 0;\
	fi
	result=$$(./scripts/validate-swagger);\
	if [ "$$result" != "{}" ]; then \
		echo "Swagger validation error: $$result"  1>&2;\
		exit 1;\
	fi
