#
# https://makefiletutorial.com
# https://clarkgrubb.com/makefile-style-guide
#

# This Makefile uses .ONESHELL option supported by Make 3.82
ifeq ($(filter oneshell,$(.FEATURES)),)
$(error error: Your version of make ($(shell make -v|head -1|cut -f 3 -d ' ')) does not support .ONESHELL)
endif

LANG := en_US.UTF-8
SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c # run '/bin/bash ... -c /bin/cmd'
.ONESHELL:
.DELETE_ON_ERROR:
.DEFAULT_GOAL := all

grails := grails -plain-output

# Testing recipes

.PHONY: all
all: clean test-unit test-integration start-wait test-engine-start test-e2e test-engine-stop

.PHONY: test
test: test-unit test-integration test-e2e ## Run unit, integration and end to end tests

test_report_html = $$(pwd)/target/test-reports/html/failed.html
.PHONY: test-unit
test-unit: ## Run unit tests
	$(grails) test-app -unit -echoOut -echoErr || (exit_code=$$?; open $(test_report_html); exit $$exit_code)

.PHONY: test-integration
test-integration: ## Run integration tests
	$(grails) test-app -integration -no-reports --stacktrace --verbose

.PHONY: test-rest
test-rest:
	$(MAKE) -C rest-e2e-tests test

.PHONY: test-e2e
test-e2e:
	$(MAKE) -C rest-e2e-tests test/e2e

.PHONY: test-stress
test-stress:
	$(MAKE) -C rest-e2e-tests test/stress

rest_srv_test_log := rest-srv-test.log
rest_srv_test_pid := rest-srv-test.pid
rest_srv_tail_pid := rest-srv-tail.pid

.PHONY: test-engine-start
test-engine-start: ## Run Grails test app
	export AWS_PROFILE=automation-user-streamr-dev
	nohup grails test run-app --non-interactive > $(rest_srv_test_log) &
	echo $$! > $(rest_srv_test_pid)
	tail -f $(rest_srv_test_log) &
	echo $$! > $(rest_srv_tail_pid)

.PHONY: test-engine-stop
test-engine-stop: ## Kill processes started by test-engine-start
	kill $(shell cat $(rest_srv_test_pid))
	rm -rf $(rest_srv_test_pid)
	kill $(shell cat $(rest_srv_tail_pid))
	rm -rf $(rest_srv_tail_pid)

# Development recipes

.PHONY: compile
compile: ## Compile code
	$(grails) compile

.PHONY: dependency-report
dependency-report: ## Generate Grails dependency report to stdout and dependencies.txt
	$(grails) dependency-report | tee dependencies.txt

.PHONY: factory-reset
factory-reset: ## Run streamr-docker-dev factory-reset
	streamr-docker-dev factory-reset

.PHONY: wipe
wipe: ## Run streamr-docker-dev stop and wipe
	streamr-docker-dev wipe

services := mysql redis cassandra parity-node0 parity-sidechain-node0 bridge data-union-server broker-node-storage-1 nginx smtp platform
.PHONY: start
start: ## Run streamr-docker-dev start ...
	streamr-docker-dev start $(services)

.NOTPARALLEL: start-wait
.PHONY: start-wait
start-wait: ## Run streamr-docker-dev start ... --wait
	streamr-docker-dev start $(services) --wait

.PHONY: stop
stop: ## Run streamr-docker-dev stop
	streamr-docker-dev stop

.PHONY: pull
pull: ## Run streamr-docker-dev pull
	streamr-docker-dev pull

.PHONY: ps
ps: ## Run streamr-docker-dev ps
	streamr-docker-dev ps

.PHONY: update
update: ## Run streamr-docker-dev update
	streamr-docker-dev update

shell-%: ## Run docker shell. Example: 'make shell-redis'
	streamr-docker-dev  shell $*

.SILENT: db-diff
.PHONY: db-diff
db-diff: ## Run Grails 'grails dbm-gorm-diff' with extras. WARNING! This command is destructive.
	echo "please enter a description of the change (no spaces, separated by - char, for example: mv-secuser-to-profile)"
	read -e description
	if [ -z "$$description" ]; then \
		echo "db-diff: description is required" 1>&2
		exit 1
	fi
	export migration_file="$$(date +%Y-%m-%d)-$$description.groovy"
	export migration_path="grails-app/migrations/core/$$migration_file"
	export changelog_path="grails-app/migrations/changelog.groovy"
	grails dbm-gorm-diff "core/$$migration_file" --add --stacktrace
	echo "package core" > "$$migration_path.new"
	cat "$$migration_path" >> "$$migration_path.new"
	mv "$$migration_path.new" "$$migration_path"
	sed -i '' -e '/^$$/d' "$$changelog_path"
	sed -i '' \
		-e '/^$$/d' \
		-e 's/[[:space:]](generated)//' \
		"$$migration_path"
	sed -i '' \
		-E 's/^	changeSet\(author: "([a-zA-Z]+)", id: "[0-9]{13,14}-([0-9])"\) \{$$/	changeSet\(author: "\1", id: "'"$$description"'-\2"\) \{/g' \
		"$$migration_path"
# comments for sed scripts above per regex
# 1. remove empty lines
# 2. replace " (generated)" with ""
# 3. replace Grails generated numeric (len 13-14) changeset id with $DESCRIPTION

# db-diff TODO:
# Consider adding:
#	git add "$$migration_path" "$$changelog_path"
# ...to the end of the recipe, but how would db-diff-revert work then?

.PHONY: db-diff-revert
db-diff-revert: ## Remove files generated by db-diff. WARNING! This command is destructive.
	git clean -f grails-app/migrations/core
	git checkout grails-app/migrations/changelog.groovy

.PHONY: db-update
db-update:
	grails test dbm-update

.PHONY: db-rollback-1
db-rollback-1:
	grails dbm-rollback-count 1

# Docker recipes

.PHONY: docker-build-dev
docker-build-dev: ## Build Docker dev container
	grails war
	docker build -t streamr/engine-and-editor:dev .

.PHONY: docker-push-dev
docker-push-dev: docker-build-dev ## Push Docker dev container to registry
	docker push streamr/engine-and-editor:dev

.PHONY: docker-run-dev
docker-run-dev: ## Run Docker dev container locally
	docker run -i -t -d --rm -p 8081:8081/tcp streamr/engine-and-editor:dev

.PHONY: docker-login
docker-login: ## Login with Docker
	docker login -u TODO_DOCKER_USER -p TODO_DOCKER_PASS

# Auxiliary recipes

.PHONY: clean
clean: ## Remove all files created by this Makefile
	rm -rf tomcat.8081/work
	rm -rf target
	rm -rf .slcache
	rm -rf "$$HOME/.grails"
	rm -rf $(rest_srv_test_log)
	$(grails) clean-all

.PHONY: clean-all
clean-all: clean
	$(MAKE) -C rest-e2e-tests clean

.PHONY: help
help: ## Show Help
	@grep -E '^[a-zA-Z_-]+%?:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "%-20s %s\n", $$1, $$2}'|sort
