# Use official Tomcat 7 runtime as base image
FROM tomcat:7.0-jre8-alpine

# Install dependencies
#   bash: required by wait_for_it.sh script
#   mysql: required for waiting for database dumps to be done
RUN apk update
RUN apk add openjdk8
RUN apk add bash mysql-client curl
RUN sed -i "s/port=\"8080\"/port=\"8081\"/g" /usr/local/tomcat/conf/server.xml
# Copy wait-for-it.sh script
COPY docker/wait-for-it.sh /usr/local/tomcat/bin/wait-for-it.sh

# Copy pre-built ROOT.war into container as streamr-core.war
COPY target/ROOT.war /usr/local/tomcat/webapps/streamr-core.war

# Default values for ENV variables
ENV STREAMR_URL http://10.200.10.1
ENV CP_URL http://10.200.10.1:8085/communities/
ENV ETHEREUM_NETWORKS_LOCAL http://10.200.10.1:8545
ENV SMTP_HOST smtp

# Flags to pass to the JVM
ENV CATALINA_OPTS -Dstreamr.database.user=root \
    -Dstreamr.database.password=password \
    -Dstreamr.database.host=mysql \
    -Dstreamr.database.name=core_test\
    -Dstreamr.redis.hosts=redis \
    -Dstreamr.cassandra.hosts=cassandra \
    -Dstreamr.url=${STREAMR_URL} \
    -Dstreamr.cps.url=${CP_URL} \
    -Dstreamr.ethereum.networks.local=${ETHEREUM_NETWORKS_LOCAL} \
    -Dgrails.mail.host=${SMTP_HOST} \
    -Dstreamr.fileUpload.s3.bucket=${S3_BUCKET} \
    -Daws.accessKeyId=${AWS_ACCESS_KEY_ID} \
    -Daws.secretKey=\'${AWS_SECRET_ACCESS_KEY}\'
EXPOSE 8081
# Wait for MySQL server, MySQL dumps, and Cassandra to be ready
CMD ["sh", "-c", "wait-for-it.sh mysql:3306 --timeout=120 && while ! mysql --user=root --host=mysql --password=password core_test -e \"SELECT 1;\"; do echo 'waiting for db'; sleep 1; done && wait-for-it.sh cassandra:9042 --timeout=120 && catalina.sh run"]
